/**
 * Advanced elements batch 2 — appended via advancedElementRegistry.js only.
 */

const stackOnly = ['stack'];
const desktop = (patch) => ({ desktop: { ...patch } });

const DEFAULT_GRID_ITEMS = [
  { id: 'grid-1', title: 'Feature one', text: 'Short supporting copy for column one.' },
  { id: 'grid-2', title: 'Feature two', text: 'Short supporting copy for column two.' },
  { id: 'grid-3', title: 'Feature three', text: 'Short supporting copy for column three.' },
];

const DEFAULT_FEATURE_ITEMS = [
  { id: 'feat-1', icon: '✓', title: 'Multi-carrier shipping', text: 'Compare rates and book in one click.' },
  { id: 'feat-2', icon: '✓', title: 'Branded tracking', text: 'Keep customers informed automatically.' },
  { id: 'feat-3', icon: '✓', title: 'COD reconciliation', text: 'Match remittance without spreadsheets.' },
];

const DEFAULT_TABLE_HEADERS = ['Feature', 'Starter', 'Pro'];
const DEFAULT_TABLE_ROWS = [
  ['Monthly orders', '500', '5,000'],
  ['API access', '—', '✓'],
  ['Dedicated support', '—', '✓'],
];

export const BATCH2_EXTRA_CARDS = [
  { id: 'container_box', label: 'Container', icon: '▭', supported: true },
  { id: 'grid_block', label: 'Grid', icon: '⊞', supported: true },
  { id: 'alert_notice', label: 'Alert', icon: '!', supported: true },
  { id: 'badge_label', label: 'Badge', icon: '●', supported: true },
  { id: 'counter_block', label: 'Counter', icon: '#', supported: true },
  { id: 'progress_bar', label: 'Progress', icon: '▬', supported: true },
  { id: 'rating_stars', label: 'Rating', icon: '★', supported: true },
  { id: 'testimonial_card', label: 'Testimonial', icon: '❝', supported: true },
  { id: 'pricing_card', label: 'Pricing Card', icon: '$', supported: true },
  { id: 'newsletter_form', label: 'Newsletter', icon: '✉', supported: true },
  { id: 'whatsapp_button', label: 'WhatsApp', icon: 'WA', supported: true },
  { id: 'countdown_timer', label: 'Countdown', icon: '⏱', supported: true },
  { id: 'html_block', label: 'HTML', icon: '</>', supported: true },
  { id: 'code_block', label: 'Code', icon: '{ }', supported: true },
  { id: 'lottie_animation', label: 'Lottie', icon: '◌', supported: true },
  { id: 'logo_block', label: 'Logo', icon: 'LG', supported: true },
  { id: 'feature_list', label: 'Feature List', icon: '☰', supported: true },
  { id: 'table_pro', label: 'Table Pro', icon: 'T+', supported: true },
];

/** @type {Record<string, object>} */
export const BATCH2_WEBSITE_WIDGETS = {
  container_box: {
    type: 'container_box',
    label: 'Container',
    allowedParents: stackOnly,
    defaultProps: {
      title: 'Content box',
      body: 'Styled wrapper for grouped content. Edit background and spacing in the Style tab.',
      align: 'left',
    },
    defaultStyle_json: desktop({
      layout: { flexDirection: 'column', gap: 12, width: '100%' },
      spacing: { padding: '24px 22px' },
      border: { radius: '14px', width: '1px', color: 'rgba(15,23,42,0.08)' },
      background: { backgroundColor: '#f8fafc' },
      effects: { boxShadow: '0 8px 28px rgba(15, 23, 42, 0.06)' },
    }),
    supportsData: false,
    supportsActions: false,
  },
  grid_block: {
    type: 'grid_block',
    label: 'Grid',
    allowedParents: stackOnly,
    defaultProps: { columns: 3, gapPx: 16, mobileStack: true, items: DEFAULT_GRID_ITEMS },
    defaultStyle_json: desktop({ layout: { width: '100%' } }),
    supportsData: false,
    supportsActions: false,
  },
  alert_notice: {
    type: 'alert_notice',
    label: 'Alert',
    allowedParents: stackOnly,
    defaultProps: {
      variant: 'info',
      title: 'Heads up',
      message: 'Use alerts for shipping delays, maintenance, or success messages.',
      showClose: true,
    },
    defaultStyle_json: desktop({ layout: { width: '100%' } }),
    supportsData: false,
    supportsActions: false,
  },
  badge_label: {
    type: 'badge_label',
    label: 'Badge',
    allowedParents: stackOnly,
    defaultProps: { text: 'New', variant: 'primary', size: 'md', href: '' },
    defaultStyle_json: desktop({ layout: { display: 'inline-flex' } }),
    supportsData: false,
    supportsActions: false,
  },
  counter_block: {
    type: 'counter_block',
    label: 'Counter',
    allowedParents: stackOnly,
    defaultProps: {
      value: '10M+',
      prefix: '',
      suffix: '',
      label: 'Shipments delivered',
      description: 'Across India and growing',
    },
    defaultStyle_json: desktop({ layout: { width: '100%' } }),
    supportsData: false,
    supportsActions: false,
  },
  progress_bar: {
    type: 'progress_bar',
    label: 'Progress Bar',
    allowedParents: stackOnly,
    defaultProps: { label: 'On-time delivery', percentage: 92, helperText: 'Last 30 days' },
    defaultStyle_json: desktop({ layout: { width: '100%' } }),
    supportsData: false,
    supportsActions: false,
  },
  rating_stars: {
    type: 'rating_stars',
    label: 'Rating',
    allowedParents: stackOnly,
    defaultProps: { rating: 4.8, maxStars: 5, reviewText: '2,400+ reviews' },
    defaultStyle_json: desktop({ layout: { width: '100%' } }),
    supportsData: false,
    supportsActions: false,
  },
  testimonial_card: {
    type: 'testimonial_card',
    label: 'Testimonial',
    allowedParents: stackOnly,
    defaultProps: {
      name: 'Priya Sharma',
      role: 'Founder, D2C brand',
      message: 'We cut delivery issues by 40% in the first quarter. The ops team finally has one dashboard.',
      avatarSrc: '/builder-placeholder.svg',
      rating: 5,
    },
    defaultStyle_json: desktop({
      layout: { flexDirection: 'column', gap: 12, width: '100%' },
      spacing: { padding: '22px 20px' },
      border: { radius: '16px', width: '1px', color: 'rgba(15,23,42,0.08)' },
      background: { backgroundColor: '#ffffff' },
      effects: { boxShadow: '0 10px 32px rgba(15, 23, 42, 0.07)' },
    }),
    supportsData: false,
    supportsActions: false,
  },
  pricing_card: {
    type: 'pricing_card',
    label: 'Pricing Card',
    allowedParents: stackOnly,
    defaultProps: {
      planName: 'Pro',
      price: '$49',
      period: '/month',
      description: 'For growing brands with automation needs.',
      features: '5,000 orders / mo\nPriority support\nAPI access',
      ctaText: 'Start Pro',
      ctaHref: '#',
      popular: true,
    },
    defaultStyle_json: desktop({
      layout: { flexDirection: 'column', gap: 12, width: '100%' },
      spacing: { padding: '26px 22px' },
      border: { radius: '16px', width: '1px', color: 'rgba(15,23,42,0.08)' },
      background: { backgroundColor: '#ffffff' },
      effects: { boxShadow: '0 12px 40px rgba(15, 23, 42, 0.08)' },
    }),
    supportsData: false,
    supportsActions: false,
  },
  newsletter_form: {
    type: 'newsletter_form',
    label: 'Newsletter',
    allowedParents: stackOnly,
    defaultProps: {
      heading: 'Stay in the loop',
      text: 'Weekly tips on shipping, COD, and growth — no spam.',
      emailPlaceholder: 'you@company.com',
      buttonText: 'Subscribe',
    },
    defaultStyle_json: desktop({
      layout: { flexDirection: 'column', gap: 14, width: '100%' },
      spacing: { padding: '24px 22px' },
      border: { radius: '14px', width: '1px', color: 'rgba(15,23,42,0.08)' },
      background: { backgroundColor: '#f1f5f9' },
    }),
    supportsData: false,
    supportsActions: false,
  },
  whatsapp_button: {
    type: 'whatsapp_button',
    label: 'WhatsApp',
    allowedParents: stackOnly,
    defaultProps: {
      phone: '919876543210',
      message: 'Hi, I would like to know more about your shipping platform.',
      buttonText: 'Chat on WhatsApp',
      floating: false,
    },
    defaultStyle_json: desktop({ layout: { width: '100%' } }),
    supportsData: false,
    supportsActions: false,
  },
  countdown_timer: {
    type: 'countdown_timer',
    label: 'Countdown',
    allowedParents: stackOnly,
    defaultProps: {
      targetIso: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
      label: 'Offer ends in',
    },
    defaultStyle_json: desktop({ layout: { width: '100%' } }),
    supportsData: false,
    supportsActions: false,
  },
  html_block: {
    type: 'html_block',
    label: 'HTML Block',
    allowedParents: stackOnly,
    defaultProps: {
      html: '<p><strong>Custom HTML</strong> — edit in the inspector. Scripts are stripped on render.</p>',
      css: '',
    },
    defaultStyle_json: desktop({ layout: { width: '100%' } }),
    supportsData: false,
    supportsActions: false,
  },
  code_block: {
    type: 'code_block',
    label: 'Code Block',
    allowedParents: stackOnly,
    defaultProps: {
      language: 'javascript',
      code: "const greeting = 'Hello from Builder';\nconsole.log(greeting);",
    },
    defaultStyle_json: desktop({ layout: { width: '100%' } }),
    supportsData: false,
    supportsActions: false,
  },
  lottie_animation: {
    type: 'lottie_animation',
    label: 'Lottie',
    allowedParents: stackOnly,
    defaultProps: { jsonUrl: '', widthPx: 240, heightPx: 240, alt: 'Animation' },
    defaultStyle_json: desktop({ layout: { width: '100%' } }),
    supportsData: false,
    supportsActions: false,
  },
  logo_block: {
    type: 'logo_block',
    label: 'Logo',
    allowedParents: stackOnly,
    defaultProps: {
      src: '/builder-placeholder.svg',
      alt: 'Company logo',
      href: '/',
      widthPx: 160,
      logo: {
        lightLogoUrl: '/builder-placeholder.svg',
        darkLogoUrl: '',
        alt: 'Company logo',
        link: '/',
        width: 160,
        height: 'auto',
      },
      meta: { brandLogo: true, logoTheme: 'auto' },
    },
    defaultStyle_json: desktop({ layout: { display: 'inline-flex' } }),
    supportsData: false,
    supportsActions: false,
  },
  feature_list: {
    type: 'feature_list',
    label: 'Feature List',
    allowedParents: stackOnly,
    defaultProps: { direction: 'vertical', items: DEFAULT_FEATURE_ITEMS },
    defaultStyle_json: desktop({ layout: { width: '100%' } }),
    supportsData: false,
    supportsActions: false,
  },
  table_pro: {
    type: 'table_pro',
    label: 'Table Pro',
    allowedParents: stackOnly,
    defaultProps: { headers: DEFAULT_TABLE_HEADERS, rows: DEFAULT_TABLE_ROWS, highlightColumn: 2 },
    defaultStyle_json: desktop({ layout: { width: '100%' } }),
    supportsData: false,
    supportsActions: false,
  },
};

export const BATCH2_BLOCK_NODE_TYPES = Object.keys(BATCH2_WEBSITE_WIDGETS);
