/**
 * Product Detail Page (PDP) widgets — ecommerce blocks for product-detail templates.
 */

const stackOnly = ['stack'];
const desktop = (patch) => ({ desktop: { ...patch } });

export const PDP_ELEMENT_CARDS = [
  { id: 'pdp_breadcrumbs', label: 'PDP Breadcrumbs', icon: '›', supported: true },
  { id: 'pdp_gallery', label: 'Product Gallery', icon: '🖼', supported: true },
  { id: 'pdp_image_zoom', label: 'Image Zoom', icon: '🔍', supported: true },
  { id: 'pdp_variant_selector', label: 'Variant Selector', icon: '◫', supported: true },
  { id: 'pdp_price', label: 'Price Block', icon: '$', supported: true },
  { id: 'pdp_sale_badge', label: 'Sale Badge', icon: '%', supported: true },
  { id: 'pdp_stock', label: 'Stock Indicator', icon: '●', supported: true },
  { id: 'pdp_quantity', label: 'Quantity', icon: '#', supported: true },
  { id: 'pdp_add_to_cart', label: 'Add To Cart', icon: '🛒', supported: true },
  { id: 'pdp_description', label: 'Description', icon: '¶', supported: true },
  { id: 'pdp_specifications', label: 'Specifications', icon: '☰', supported: true },
  { id: 'pdp_reviews', label: 'Reviews', icon: '★', supported: true },
  { id: 'pdp_related', label: 'Related Products', icon: '⊞', supported: true },
  { id: 'pdp_delivery_eta', label: 'Delivery ETA', icon: '🚚', supported: true },
];

const basePdpProps = {
  showWhenOutOfStock: true,
  layout: 'default',
};

/** @type {Record<string, object>} */
export const PDP_WEBSITE_WIDGETS = {
  pdp_breadcrumbs: {
    type: 'pdp_breadcrumbs',
    label: 'PDP Breadcrumbs',
    allowedParents: stackOnly,
    defaultProps: { ...basePdpProps, showHome: true, showCategory: true },
    defaultStyle_json: desktop({ layout: { width: '100%' } }),
    supportsData: false,
    supportsActions: false,
  },
  pdp_gallery: {
    type: 'pdp_gallery',
    label: 'Product Gallery',
    allowedParents: stackOnly,
    defaultProps: { ...basePdpProps, layout: 'thumbnails-left', enableSwipe: true, lazyLoad: true },
    defaultStyle_json: desktop({ layout: { width: '100%' } }),
    supportsData: false,
    supportsActions: false,
  },
  pdp_image_zoom: {
    type: 'pdp_image_zoom',
    label: 'Image Zoom',
    allowedParents: stackOnly,
    defaultProps: { ...basePdpProps, zoomLevel: 2, lightbox: true },
    defaultStyle_json: desktop({ layout: { width: '100%' } }),
    supportsData: false,
    supportsActions: false,
  },
  pdp_variant_selector: {
    type: 'pdp_variant_selector',
    label: 'Variant Selector',
    allowedParents: stackOnly,
    defaultProps: { ...basePdpProps, layout: 'pills', optionKeys: [] },
    defaultStyle_json: desktop({ layout: { width: '100%' } }),
    supportsData: false,
    supportsActions: false,
  },
  pdp_price: {
    type: 'pdp_price',
    label: 'Price Block',
    allowedParents: stackOnly,
    defaultProps: { ...basePdpProps, showCompareAt: true, showCurrency: true },
    defaultStyle_json: desktop({ layout: { width: '100%' } }),
    supportsData: false,
    supportsActions: false,
  },
  pdp_sale_badge: {
    type: 'pdp_sale_badge',
    label: 'Sale Badge',
    allowedParents: stackOnly,
    defaultProps: { ...basePdpProps, label: 'Sale', hideWhenNotOnSale: true },
    defaultStyle_json: desktop({ layout: { width: '100%' } }),
    supportsData: false,
    supportsActions: false,
  },
  pdp_stock: {
    type: 'pdp_stock',
    label: 'Stock Indicator',
    allowedParents: stackOnly,
    defaultProps: { ...basePdpProps, lowStockThreshold: 5, hideWhenOutOfStock: false },
    defaultStyle_json: desktop({ layout: { width: '100%' } }),
    supportsData: false,
    supportsActions: false,
  },
  pdp_quantity: {
    type: 'pdp_quantity',
    label: 'Quantity',
    allowedParents: stackOnly,
    defaultProps: { ...basePdpProps, min: 1, max: 99 },
    defaultStyle_json: desktop({ layout: { width: '100%' } }),
    supportsData: false,
    supportsActions: false,
  },
  pdp_add_to_cart: {
    type: 'pdp_add_to_cart',
    label: 'Add To Cart',
    allowedParents: stackOnly,
    defaultProps: { ...basePdpProps, label: 'Add to cart', soldOutLabel: 'Sold out' },
    defaultStyle_json: desktop({ layout: { width: '100%' } }),
    supportsData: false,
    supportsActions: false,
  },
  pdp_description: {
    type: 'pdp_description',
    label: 'Description',
    allowedParents: stackOnly,
    defaultProps: { ...basePdpProps, collapsible: false },
    defaultStyle_json: desktop({ layout: { width: '100%' } }),
    supportsData: false,
    supportsActions: false,
  },
  pdp_specifications: {
    type: 'pdp_specifications',
    label: 'Specifications',
    allowedParents: stackOnly,
    defaultProps: { ...basePdpProps, layout: 'table' },
    defaultStyle_json: desktop({ layout: { width: '100%' } }),
    supportsData: false,
    supportsActions: false,
  },
  pdp_reviews: {
    type: 'pdp_reviews',
    label: 'Reviews',
    allowedParents: stackOnly,
    defaultProps: {
      ...basePdpProps,
      pageSize: 5,
      sortBy: 'rating',
      showAverage: true,
      allowRatingFilter: true,
    },
    defaultStyle_json: desktop({ layout: { width: '100%' } }),
    supportsData: false,
    supportsActions: false,
  },
  pdp_related: {
    type: 'pdp_related',
    label: 'Related Products',
    allowedParents: stackOnly,
    defaultProps: {
      ...basePdpProps,
      limit: 4,
      useCategory: true,
      useTags: false,
      columns: 2,
    },
    defaultStyle_json: desktop({ layout: { width: '100%' } }),
    supportsData: false,
    supportsActions: false,
  },
  pdp_delivery_eta: {
    type: 'pdp_delivery_eta',
    label: 'Delivery ETA',
    allowedParents: stackOnly,
    defaultProps: { ...basePdpProps, prefix: 'Delivery in', suffix: 'business days' },
    defaultStyle_json: desktop({ layout: { width: '100%' } }),
    supportsData: false,
    supportsActions: false,
  },
};
