CREATE TABLE IF NOT EXISTS reusable_blocks (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  project_id BIGINT UNSIGNED NOT NULL,
  name VARCHAR(255) NOT NULL,
  snapshot_json JSON NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_reusable_blocks_project (project_id),
  CONSTRAINT fk_reusable_blocks_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE
);

